### ISSUE TITLE
Would you mind pushing a dev build to curseforge.

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [elytra/Opaline#3]
have talked to them alot but they wont accept my pack and even tried via submitting the mod for approval

**Comment by Boundarybreaker** [comment]
v1.2 is almost done! I'm just making sure there are no issues, and the final will be up as soon as I'm done with it.

**Comment by LemmaEOF** [comment]
Oops, didn't realize this is on Opaline, not InRed. Sorry about that.

Please don't submit a mod you didn't make and don't have permission to upload, ever. Opaline is not finished, in any way, shape, or form. I can't see why you would want a build when the two most important blocks in the mod, the block that lets you get enchantments into lazurite and the block that lets you apply enchantments from lazurite to an item, don't exist in any form. Opaline will not be adding any worldgen, so there is no reason to just add it to your pack later. Please be patient while I finish the mod.

Please do not attempt to upload this mod in its unfinished state again. Due to the LGPL v3 license this mod is under, I can technically not stop you from doing this, but it would be incredibly rude and disrespectful, and likely kill what motivation I have to work on the project further.

**Comment by CrankySupertoonArchive** [comment]
Sorry i meant my modpack, when i went through the mod approval process to be in a spreadshhet. Pretty much it tells them its allowed to be in packs.

**Comment by LemmaEOF** [comment]
Curse is very paranlid about mods. They pretty much won't allow any non-Curse mod to be added to a modpack unless it's a non-curse version of a mod already on curse. I'm still not going to be uploading a development build, because there's nothing really to do with opaline at the moment.
